# Generated by Django 5.0.3 on 2024-03-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_project_author_alter_project_contributors_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Issue",
        ),
    ]
