# Generated by Django 5.0.3 on 2024-03-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_delete_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
