# Generated by Django 5.0.3 on 2024-03-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="title",
            field=models.CharField(default="titre", max_length=128),
            preserve_default=False,
        ),
    ]
