# Generated by Django 5.0.3 on 2024-03-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0002_comment_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="title",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
