# Generated by Django 5.0.3 on 2024-03-14 08:29

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0003_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customuser",
            name="date_of_birth_must_be_in_past",
        ),
        migrations.RemoveConstraint(
            model_name="customuser",
            name="user_must_be_over_15_years_old",
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.CheckConstraint(
                check=models.Q(("date_of_birth__lte", datetime.date(2024, 3, 14))),
                name="Votre naissance n'a pas encore eu lieu !!!",
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.CheckConstraint(
                check=models.Q(("date_of_birth__lte", datetime.date(2009, 3, 18))),
                name="Vous devez avoir plus de 15 ans !!!",
            ),
        ),
    ]
