# Generated by Django 5.0.3 on 2024-03-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0002_alter_issue_title_alter_issue_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="contributor_assigned",
            field=models.CharField(
                blank=True,
                choices=[("BUG", "BUG"), ("FEATURE", "FEATURE"), ("TASK", "TASK")],
                default="",
                max_length=20,
            ),
        ),
    ]
