# Generated by Django 5.0.3 on 2024-03-20 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0003_alter_issue_contributor_assigned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="contributor_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributor_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
